# Generated by Django 5.2.4 on 2025-08-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
    ]
