# Generated by Django 5.2.4 on 2025-08-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20250801_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book'), ('can_create', 'Can create book'), ('can_edit', 'Can edit book'), ('can_delete', 'Can delete book'), ('can_view_all_books', 'Can view all books'), ('can_manage_authors', 'Can manage book authors'), ('can_bulk_operations', 'Can perform bulk operations')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
