# Generated by Django 5.2.4 on 2025-08-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options'),
    ]

    operations = [
    ]
